import {
  Html5Original,
  Css3Original,
  JavascriptOriginal,
  TypescriptOriginal,
  ReactOriginal,
  TailwindcssOriginal,
  NextjsOriginal,
  VitejsOriginal,
  NodejsOriginalWordmark,
  SpringOriginal,
  NpmOriginalWordmark,
  GitOriginal,
  DockerPlain,
  FirebaseOriginal,
  NginxOriginal,
  MysqlOriginalWordmark,
  DbeaverOriginal,
  JavaOriginal,
  CsharpOriginal,
  PythonOriginal,
  RustOriginal,
  CplusplusOriginal,
  TauriOriginal,
  WasmOriginal,
  BlenderOriginal,
  UnityOriginal,
  P5jsOriginal,
  ArduinoOriginalWordmark,
  MarkdownOriginal,
  ApacheOriginal,
  AmazonwebservicesOriginalWordmark,
  AstroOriginal,
  AxiosPlain,
  BashOriginal,
  COriginal,
  CloudflareOriginal,
  DotnetcoreOriginal,
  EslintOriginal,
  FigmaOriginal,
  FlutterOriginal,
  GithubOriginal,
  GithubactionsOriginal,
  GitlabOriginal,
  InkscapeOriginal,
  IntellijOriginal,
  MongodbOriginal,
  NetlifyOriginal,
  PhpOriginal,
  PostcssOriginal,
  PostgresqlOriginal,
  PostmanOriginal,
  PowershellPlain,
  SqliteOriginal,
  VercelOriginal,
  VisualstudioOriginal,
  VscodeOriginal,
  WebpackOriginal,
  YamlOriginal,
  SurrealdbOriginal,
  DartOriginal,
} from "devicons-react";
import { FunctionComponent } from "react";

interface Technology {
  label: string;
  icon: FunctionComponent;
}

export const technologies: Technology[] = [
  // --- Languages & Runtimes ---
  { label: "Rust", icon: RustOriginal },
  { label: "Java", icon: JavaOriginal },
  { label: "TypeScript", icon: TypescriptOriginal },
  { label: "JavaScript", icon: JavascriptOriginal },
  { label: "Python", icon: PythonOriginal },
  { label: "C++", icon: CplusplusOriginal },
  { label: "C#", icon: CsharpOriginal },
  { label: "C", icon: COriginal },
  { label: "PHP", icon: PhpOriginal },
  { label: "Dart", icon: DartOriginal },
  { label: "Node.js", icon: NodejsOriginalWordmark },
  { label: "WASM", icon: WasmOriginal },

  // --- Frameworks & Libraries ---
  { label: "React", icon: ReactOriginal },
  { label: "Next.js", icon: NextjsOriginal },
  { label: "Spring", icon: SpringOriginal },
  { label: "Tailwind", icon: TailwindcssOriginal },
  { label: "Vite", icon: VitejsOriginal },
  { label: "Tauri", icon: TauriOriginal },
  { label: "Astro", icon: AstroOriginal },
  { label: "Flutter", icon: FlutterOriginal },
  { label: ".NET Core", icon: DotnetcoreOriginal },
  { label: "p5.js", icon: P5jsOriginal },
  { label: "Axios", icon: AxiosPlain },

  // --- Databases & Backend ---
  { label: "MySQL", icon: MysqlOriginalWordmark },
  { label: "PostgreSQL", icon: PostgresqlOriginal },
  { label: "MongoDB", icon: MongodbOriginal },
  { label: "SQLite", icon: SqliteOriginal },
  { label: "Firebase", icon: FirebaseOriginal },
  { label: "SurrealDB", icon: SurrealdbOriginal },
  { label: "DBeaver", icon: DbeaverOriginal },

  // --- Infrastructure & DevOps ---
  { label: "Docker", icon: DockerPlain },
  { label: "NGINX", icon: NginxOriginal },
  { label: "Apache", icon: ApacheOriginal },
  { label: "AWS", icon: AmazonwebservicesOriginalWordmark },
  { label: "Vercel", icon: VercelOriginal },
  { label: "Netlify", icon: NetlifyOriginal },
  { label: "Cloudflare", icon: CloudflareOriginal },
  { label: "GitHub Actions", icon: GithubactionsOriginal },

  // --- Tools & Workflow ---
  { label: "Git", icon: GitOriginal },
  { label: "GitHub", icon: GithubOriginal },
  { label: "GitLab", icon: GitlabOriginal },
  { label: "NPM", icon: NpmOriginalWordmark },
  { label: "Postman", icon: PostmanOriginal },
  { label: "Webpack", icon: WebpackOriginal },
  { label: "PostCSS", icon: PostcssOriginal },
  { label: "ESLint", icon: EslintOriginal },
  { label: "Bash", icon: BashOriginal },
  { label: "PowerShell", icon: PowershellPlain },
  { label: "YAML", icon: YamlOriginal },
  { label: "Markdown", icon: MarkdownOriginal },

  // --- Creative & IDEs ---
  { label: "Figma", icon: FigmaOriginal },
  { label: "Blender", icon: BlenderOriginal },
  { label: "Unity", icon: UnityOriginal },
  { label: "Inkscape", icon: InkscapeOriginal },
  { label: "VS Code", icon: VscodeOriginal },
  { label: "Visual Studio", icon: VisualstudioOriginal },
  { label: "IntelliJ", icon: IntellijOriginal },
  { label: "Arduino", icon: ArduinoOriginalWordmark },
  { label: "HTML5", icon: Html5Original },
  { label: "CSS3", icon: Css3Original },
];
